<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-38MES30" failures="1" tests="6" name="io.swagger.petstore.PetStoreTest" time="4.124" errors="0" timestamp="2019-09-09T12:53:10 EEST" skipped="0">
  <testcase classname="io.swagger.petstore.PetStoreTest" name="uploadImage" time="0.621"/>
  <testcase classname="io.swagger.petstore.PetStoreTest" name="getInvalidPet" time="0.288"/>
  <testcase classname="io.swagger.petstore.PetStoreTest" name="petTest" time="1.892"/>
  <testcase classname="io.swagger.petstore.PetStoreTest" name="deleteNotPresentPet" time="0.383"/>
  <testcase classname="io.swagger.petstore.PetStoreTest" name="getPetByStatus" time="0.590"/>
  <testcase classname="io.swagger.petstore.PetStoreTest" name="addPetWithInvalidData" time="0.350">
    <failure message="The following asserts failed:
	StatusCode isn&#039;t equals expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
StatusCode isn't equals expected [200] but found [500]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at asertions.BaseAssertions.baseAssert(BaseAssertions.java:20)
at business.PetBL.addPetWithInvalidDataTest(PetBL.java:71)
at io.swagger.petstore.PetStoreTest.addPetWithInvalidData(PetStoreTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
    </failure>
  </testcase> <!-- addPetWithInvalidData -->
</testsuite> <!-- io.swagger.petstore.PetStoreTest -->
